config/routes.rb
Rails.application.routes.draw do

  root 'cuisines#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :cuisines, only: [:index, :show]
  resources :recipes, only: [:show, :edit, :update, :destroy]
    

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base

  has_many :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :cuisine

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
  def editor?
    self.role == 'editor'
  end
  
  def admin?
    self.role == 'admin'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   helper_method :current_user
 
   def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end 

   def require_user
     redirect_to '/login' unless current_user
   end 
  
  def require_editor
    redirect_to '/' unless current_user.editor?
  end
  
  def require_admin
    
  end
 
   

end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

   def index
    @cuisines = Cuisine.all
  end 

  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = @cuisine.recipes
  end 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  
  before_action :require_editor, only: [:show, :edit]

  before_action :require_admin, only: [:destroy]
  
  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render 'edit'
      end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_url
  end 

  private
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end 

  def create
    puts params[:email]
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      redirect_to login_url
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        redirect_to signup_url
    end
  end 

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cuisines/index.html.erb
<div class="cuisines">
  <div class="container">
    <% @cuisines.each do |cuisine|%> 
      <div class="cuisine">
        <h2><%= cuisine.region %></h2> 
        <img class="arrow" src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/arrow.svg" width="80" height="40">
        <p><%= link_to "View Recipes", cuisine_path(cuisine) %></p>
        <%= image_tag cuisine.image %>
      </div> 
    <% end %>
  </div>
</div>

app/views/cuisines/show.html.erb
<div class="main">
  <h1 class="cuisine"><%= @cuisine.region %> Recipes</h1>
  <div class="container">
    <div class="recipes">
      <% @recipes.each do |recipe|%> 
        <div class="recipe">
          <h2 class="recipe-name"><%= recipe.name %></h2> 
          <img class="arrow" src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/arrow.svg" width="80" height="40">
          <p class="recipe-link"><%= link_to "Show Recipe", recipe_path(recipe) %></p>
          <%= image_tag recipe.image %>
        </div>
      <% end %> 
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <div class="header">
    <div class="container">

      <div class="nav">
        <% if current_user %>
          <ul>
            <li><%= current_user.email %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to "Log in", login_path %></a></li>
            <li><%= link_to "Sign up", signup_path %></a></li>
          </ul>
        <% end %>
      </div>
    
      <div class="logo">
      </div>
    
    </div>
  </div>

  <%= yield %>

  </body>
</html>

app/views/recipes/edit.html.erb
<div class="recipe-edit">
  <div class="container">
    <div class="img_container">
      <%= image_tag @recipe.image %>
    </div>

    <%= form_for(@recipe) do |f| %>
      <%= f.text_field :name %>
      <%= f.text_area :ingredients %>
      <%= f.text_area :instructions %>
      <%= f.submit "Update", :class => "form-btn" %>
    <% end %> 
    
  </div>
</div> 

app/views/recipes/show.html.erb
<div class="recipe-show">
  <div class="container">
    <h2><%= @recipe.name %></h2>
    <img class="arrow" src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/arrow.svg" width="80" height="40">
    <div class="img_container">
      <%= image_tag @recipe.image %>
    </div>
    <div class="recipe-info">
      <p class="ingredients"><%= @recipe.ingredients %></p>
      <p class="instructions"><%= @recipe.instructions %></p> 
    </div> 
    
    <% if current_user && current_user.editor? %>
    <p class="recipe-edit">
      <%= link_to "Edit Recipe", edit_recipe_path(@recipe.id) %>
    </p>
    <% end %>
    	
    
    <% if current_user && current_user.admin? %>
    <p class="recipe-delete">
      <%= link_to "Delete", recipe_path(@recipe), method: "delete" %>
    </p>
    <% end %>
    
  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <%= form_for :user, url: '/users' do |f| %>
      <%= f.text_field :first_name, :placeholder => 'First Name' %>
      <%= f.text_field :last_name, :placeholder => 'Last Name' %>
      <%= f.text_field :email, :placeholder => 'Email' %> 
      <%= f.password_field :password, :placeholder => 'Password' %> 
      <%= f.submit "Sign up", :class => "form-btn" %>
    <% end %>
  </div>
</div>